swagger: '2.0'
info:
  version: '1.0.0'
  title: '[Demo] Orders API'
  description: |
    Teamplate API conforming to adidas API Guidelines.
    This API is [documented at Apiary](http://docs.demotemplatewip.apiary.io)
    and [stored on GitHub](https://github.com/adidas-group/demo-orders-api).

schemes:
  - https

produces:
  - application/hal+json      # Representation message format
  - application/problem+json  # Error message format

paths:
  /:
    x-summary: API Root

    get:
      summary: Retrieve API Root
      description: The API Root contains the initial set of link relations.
      responses:
        200:
          description: The root of the API
          schema:
            $ref: '#/definitions/hal_root'

  /orders:
    x-summary: List of Orders

    get:
      summary: Retrieve List of Orders
      responses:
        200:
          description: The list of Orders
          schema:
            $ref: '#/definitions/hal_orders'

    post:
      summary: Create a new Order
      consumes:
        - application/json
      parameters:
        - name: Order
          in: body
          description: Order to be created
          required: true
          schema:
            $ref: '#/definitions/order'
      responses:
        201:
          description: Newly created order
          schema:
            $ref: '#/definitions/hal_order'

  /orders/{order_id}:
    x-summary: Order

    parameters:
      - name: order_id
        in: path
        description: Id of the Order
        required: true
        type: string
        x-example: 1234

      - name: fields
        in: query
        description: Comma-separated list of fields to include in the response
        required: false
        type: string
        x-example: order_number,status

    get:
      summary: Retrieve Order
      responses:
        200:
          description: A particular Order
          schema:
            $ref: '#/definitions/hal_order'

        404:
          description: The request Order wasn't found
          headers:
            Content-Type:
              type: string
              default: application/problem+json
          schema:
            $ref: '#/definitions/order_not_found'

    patch:
      summary: Update Order
      consumes:
        - application/json
      parameters:
        - name: Order
          in: body
          description: Partial order update
          required: true
          schema:
            $ref: '#/definitions/order_patch'
      responses:
        200:
          description: The Order was updated
          schema:
            $ref: '#/definitions/hal_order'

    delete:
      summary: Delete Order
      produces: []
      responses:
        204:
          description: The Order was deleted

definitions:
  #
  # API Root
  #
  hal_root:
    type: object
    allOf:
      - $ref: '#/definitions/hal_resource'
    example:
      _links:
        self:
          href: /
        orders:
          href: /orders

  #
  # Orders Resource
  #
  hal_orders:
    type: object
    allOf:
      - $ref: '#/definitions/hal_resource'
    example:
      _links:
        self:
          href: /orders

      _embedded:
        order:
          - $ref: '#/definitions/hal_order/example'

  #
  # Order Resource
  #

  # HAL Wrapper
  hal_order:
    type: object
    allOf:
      - $ref: '#/definitions/hal_resource'
      - $ref: '#/definitions/order'
    example:
      _links:
        self:
          href: /orders/1234
          
        edit:
          href: /orders/1234
          profile: https://tools.ietf.org/html/rfc5023#section-5.4.2
          
        delete: 
          href: /orders/1234
          
      order_number: 1234
      item_count: 42
      status: pending

  # Partial Order
  order_patch:
    type: object
    allOf:
      - $ref: '#/definitions/order'
    example:
      status: cancelled

  # Order
  order:
    type: object
    properties:
      orderNumber:
        type: number
      itemCount:
        type: number
      status:
        type: string
    required:
      - order_number
      - item_count
    example:
      order_number: 42
      item_count: 3
      status: pending

  # Order Not Found Error
  order_not_found:
    type: object
    allOf:
      - $ref: '#/definitions/problem_detail'
    example:
      title: 'Not Found'
      detail: 'Cannot find the requested order'
      status: 404
      instance: '/orders/1234'

  #
  # -- DO NOT EDIT BEYOND THIS POINT --
  #

  # Media Types Definitions

  #
  # application/problem+json
  #
  problem_detail:
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        type: number
      detail:
        type: string
      instance:
        type: string
    required:
      - title
      - detail

  #
  # application/hal+json defintion
  #
  hal_link_object:
    type: object
    required:
      - href
    properties:
      href:
        type: string
      templated:
        type: boolean
      type:
        type: string
      deprecation:
        type: string
      name:
        type: string
      profile:
        type: string
      title:
        type: string
      hreflang:
        type: string

  hal_curies_link:
    title: HAL Curies Link
    allOf:
      - type: object
        properties:
          templated:
            enum:
              - true
        required:
          - templated
      - $ref: '#/definitions/hal_link_object'

  hal_resource:
    title: HAL Resource Object
    type: object
    properties:
      _links:
        type: object
        additionalProperties:
          # WARN: Should be "anyOf" but "anyOf" isn't supported in Swagger 2.0
          allOf:
            - $ref: '#/definitions/hal_link_object'
            - type: array
              items:
                - $ref: '#/definitions/hal_link_object'
        properties:
          curies:
            # WARN: Should be "anyOf" but "anyOf" isn't supported in Swagger 2.0
            allOf:
              - $ref: '#/definitions/hal_curies_link'
              - type: array
                items:
                  - $ref: '#/definitions/hal_curies_link'
      _embedded:
        type: object
        additionalProperties: true
        # WARN: Apiary doesn't support circular references
        # additionalProperties:
        #   anyOf:
        #     - $ref: '#/definitions/hal_resource'
        #     - type: array
        #       items:
        #         - $ref: '#/definitions/hal_resource'