swagger: '2.0'
info:
  title: '[Demo] Oders API (WIP)'
  description: | 
    _This template is work in progress_
    
    API template conforming to the [adidas API guidelines](https://adidas-group.gitbooks.io/api-guidelines/content/).
    
  version: '0.1.0'
schemes:
  - https
basePath: /
produces:
  - application/vnd.siren+json
paths:
  /:
    x-summary: API Root

    get:
      summary: Retrieve
      responses:
        200:
          description: The root of the API.
          schema:
            $ref: '#/definitions/RootResponse'

  /orders:
    x-summary: Orders
    
    get: 
      summary: Retrieve List of Orders
      responses:
        200:
          description: List of Orders
          schema:
            $ref: '#/definitions/SirenEntity'
            
  /orders/{orderId}:
    x-summary: Order
    parameters:
      - name: orderId
        in: path
        description: Order id
        required: true
        type: string
        x-example: 4731

    get:
      summary: Retrieve a Specific Order
      responses:
        200:
          description: Specific Order
          schema:
            $ref: '#/definitions/SirenEntity'
            example:
              class:
              - order
              properties:
                orderNumber: 42
                itemCount: 3
                status: pending
              entities:
              - class:
                - items
                - collection
                rel:
                - http://x.io/rels/order-items
                href: http://api.x.io/orders/42/items
              - class:
                - info
                - customer
                rel:
                - http://x.io/rels/customer
                properties:
                  customerId: pj123
                  name: Peter Joseph
                links:
                - rel:
                  - self
                  href: http://api.x.io/customers/pj123
              actions:
              - name: add-item
                title: Add Item
                method: POST
                href: http://api.x.io/orders/42/items
                type: application/x-www-form-urlencoded
                fields:
                - name: orderNumber
                  type: hidden
                  value: '42'
                - name: productCode
                  type: text
                - name: quantity
                  type: number
              links:
              - rel:
                - self
                href: http://api.x.io/orders/42
              - rel:
                - previous
                href: http://api.x.io/orders/41
              - rel:
                - next
                href: http://api.x.io/orders/43

definitions:
  # API-specific data
  RootResponse:
    type: object
    allOf:
      - $ref: '#/definitions/SirenEntity'
      - properties:
          properties:
            $ref: '#/definitions/RootProperties'
    example:
      properties: 
        $ref: '#/definitions/RootProperties/example'
    
  RootProperties:
    type: object
    properties:
      name:
        type: string
    example:
      message: Hello World!
      
  # Siren data structures
  # DO NOT EDIT BEYOND THIS POINT
  SirenEntity:
    type: object
    properties:
      class:
        type: array
        items:
          type: string
      entities:
        type: array
        items:
          $ref: '#/definitions/SirenSubEntity'
      actions:
        type: array
        items:
          $ref: '#/definitions/SirenAction'
      links:
        type: array
        items:
          $ref: '#/definitions/SirenLink'

  SirenSubEntity:
    type: object
    properties:
      href:
        type: string
      rel:
        type: array
        items:
          type: string
      class:
        type: array
        items:
          type: string
      properties:
        type: object
      entities:
        type: array
        # Apiary Beta Warning
        #   the following should be uncommented once Apiary has the support circular references
        #items:
        #  $ref: '#/definitions/SirenSubEntity'
      actions:
        type: array
        items:
          $ref: '#/definitions/SirenAction'
      links:
        type: array
        items:
          $ref: '#/definitions/SirenLink'

  SirenAction:
    type: object
    required:
      - name
      - href
    properties:
      class:
        type: array
        items:
          type: string
      name:
        type: string
      method:
        type: string
      href:
        type: string
      title:
        type: string
      type:
        type: string
      fields:
        type: array
        items:
          $ref: '#/definitions/SirenField'

  SirenField:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      type:
        type: string
        enum:
          - hidden
          - text
          - search
          - tel
          - url
          - email
          - password
          - datetime
          - date
          - month
          - week
          - time
          - datetime-local
          - number
          - range
          - color
          - checkbox
          - radio
          - file
      title:
        type: string
      value:
        type: string

  SirenLink:
    type: object
    required:
      - rel
      - href
    properties:
      class:
        type: array
        items:
          type: string
      title:
        type: string
      rel:
        type: array
        items:
          type: string
      href:
        type: string
      type:
        type: string